name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches_ignore: []

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        stagein: "mamba install -y -n snakemake --channel conda-forge pyarrow=6.0"
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs: 
      - Linting
      - Formatting
    steps:
    - uses: actions/checkout@v2
    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .tests/integration
        snakefile: workflow/Snakefile
        args: "--configfile .tests/integration/config/config.yaml --use-conda --show-failed-logs -j 10 --conda-cleanup-pkgs cache --conda-frontend mamba"
        stagein: "conda config --get channel_priority --json"
    - name: Test report
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .tests/integration
        snakefile: workflow/Snakefile
        args: "--configfile .tests/integration/config/config.yaml --report report.zip"
